apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: document-expert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 028892270743.dkr.ecr.us-east-1.amazonaws.com/document_expert-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-creds