apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: document-expert
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: ssm-store
  target:
    name: backend-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: document-expert-backend


        