apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: ssm-store
  namespace: document-expert
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
